5.22. Сетка страниц и крупных блоков на флексах
htmlacademy-htmlcss/2518753-sedona-1 pull request #5
Opened 2024-05-15 10:16 UTC by Artem-Sobolev91

Добрый день. Не много не понял формулировку задания, возможно что то лишнее сделал, а  где то пропустил. Посмотрите пожалуйста.

2024-05-18 17:22 UTC, andreysgra requested changes
В данном проекте вся контентная область ограничена шириной 1200px и нет блоков в которых фоновый цвет тянется на всю ширину страницы, поэтому логичнее сделать общий контейнер для всего контента, например `div` с классом `,container` и в него поместить весь контент с хэдером и футером:
```
<div class="container">
  <header class="main-header"></header>

  <main class="main-container"></main>

  <footer class="main-footer"></footer>
</div>
```
В класс `.container` перенести свойства `width: 1200px; margin: 0 auto;`.

---

В этом проекте нет различий в стилизации тега `main` для главной страницы и внутренних страниц, соответственно нет необходимости использовать дополнительные классы `.main-inner` и `.main-index`, достаточно одного класса `.main-container`.

2024-05-21 14:06 UTC, Artem-Sobolev91 commented
В конечных комитах ,сам ответил на вопрос о размерах квадратов в advantages.

2024-05-22 16:58 UTC, andreysgra requested changes
Есть ошибки валидации HTML обеих страниц.

2024-05-22 16:58 UTC, andreysgra commented on index.html
> +          </li>
Здесь разметку вы переделали, и не вполне корректно.

Было вот так:
```
       <li class="advantages-item advantages-item-wide">
          <h3>Настоящий городок</h3>
          <p>Седона — не аттракцион для туристов, там течёт своя жизнь</p>
          <img src="images/photo-1.jpg" width="800" height="385" alt="улица города">
        </li>
```
Изображение должно находиться в в одном элементе списка, что и описание, но не в разных.

Такая разметка будет правильной:
```
          <li class="advantages-item advantages-item-wide">
            <div class="advantages-item-text">
              <h3>Настоящий городок</h3>
              <p>Седона — не аттракцион для туристов, там течёт своя жизнь</p>
            </div>
            <div class="advantages-item-img">
              <img src="images/photo-1.jpg" width="800" height="385" alt="улица города">
              </div>
          </li>
```

Тоже самое нужно сделать и для другого элемента списка с изображением.

2024-05-23 14:12 UTC, merged