8. Декоративные элементы
htmlacademy-htmlcss/2518753-sedona-1 pull request #8
Opened 2024-06-09 10:44 UTC by Artem-Sobolev91

2024-06-19 05:09 UTC, andreysgra requested changes

2024-06-19 05:09 UTC, andreysgra commented on styles/styles.css
> +  width: auto;
`auto` - значение по умолчанию, поэтому в данном случае в использовании `width` нет необходимости.

2024-06-19 05:09 UTC, andreysgra commented on styles/styles.css
> +.navigation-link {
Свойства этого класса разбросаны по CSS файлу. Почему бы не собрать их в одном месте?
![image](https://github.com/htmlacademy-htmlcss/2518753-sedona-1/assets/17790771/97987cf5-4e90-4059-a6e5-ad32efdcf624)

2024-06-19 05:09 UTC, andreysgra commented on styles/styles.css
> +  background-position: 50% 3.5%;
Значение `background-position` по вертикали стоит задать в `px`, а не в процентах, так как при наполнении текстом изображение будет смещаться:
![image](https://github.com/htmlacademy-htmlcss/2518753-sedona-1/assets/17790771/bdfd3eac-511d-482b-90de-614ea4c0f208)

2024-06-19 05:09 UTC, andreysgra commented on styles/styles.css
> +  background-position: top center;
Здесь тоже вместо ключевого слова `top` нужно задать значение в `px`.

2024-06-19 05:09 UTC, andreysgra commented on styles/styles.css
>  .services-item p {
1. Убрать паддинги в селекторе `.services-item p`. Таким образом решится большинство переносов текста.
2. Там, где не получаются переносы как в макете нужно добавить символ неразрывного пробела `&nbsp;`
![image](https://github.com/htmlacademy-htmlcss/2518753-sedona-1/assets/17790771/3c255729-1d59-441d-9410-ae669c20185f)

2024-06-19 05:09 UTC, andreysgra commented on styles/styles.css
> +input::placeholder {
[CSS-02.](https://up.htmlacademy.ru/htmlcss-individual/1/criteries#CSS-02) Глобальный селектор.

2024-06-19 05:09 UTC, andreysgra commented on styles/styles.css
> +  font-family: PT Sans;
1. Нет кавычек для `PT Sans`.
2. [CSS-06.](https://up.htmlacademy.ru/htmlcss-individual/1/criteries#CSS-06) Использование шрифтов. Должно быть указано типовое семейство для шрифта.

2024-06-19 05:09 UTC, andreysgra commented on styles/styles.css
> +  font-family: PT Sans;
[CSS-06.](https://up.htmlacademy.ru/htmlcss-individual/1/criteries#CSS-06) Использование шрифтов. Должно быть указано типовое семейство для шрифта.

2024-06-19 05:09 UTC, andreysgra commented on styles/styles.css
> +.social-item a :focus {
Потому что ошибка в записи:
```suggestion
.social-item a:focus {
```

2024-06-19 05:09 UTC, andreysgra commented on styles/styles.css
> +.social-item a :hover {
```suggestion
.social-item a:hover {
```

2024-06-19 05:09 UTC, andreysgra commented on styles/styles.css
> +.social-item a :active {
```suggestion
.social-item a:active {
```

2024-06-19 05:09 UTC, andreysgra commented on styles/styles.css
> +  font-family: PT Sans;
[CSS-06.](https://up.htmlacademy.ru/htmlcss-individual/1/criteries#CSS-06) Использование шрифтов. Должно быть указано типовое семейство для шрифта.

2024-06-19 05:09 UTC, andreysgra commented on styles/styles.css
> +  font-family: PT Sans;
[CSS-06.](https://up.htmlacademy.ru/htmlcss-individual/1/criteries#CSS-06) Использование шрифтов. Должно быть указано типовое семейство для шрифта.

2024-06-19 05:09 UTC, andreysgra commented on styles/styles.css
> +  border-color: #68a2Ca;
```suggestion
  border-color: #68a2ca;
```

2024-06-19 05:09 UTC, andreysgra commented on styles/styles.css
> +  opacity: 30%;
```suggestion
  opacity: 0.3;
```

2024-06-19 05:09 UTC, andreysgra commented on styles/styles.css
> +}
Единообразие оформления кода: для цвета у которого есть прозрачность используется либо `rgba`, либо `hsla`, но не одновременно обе функции (в других местах вы используете `rgba`).

2024-06-19 05:09 UTC, andreysgra commented on styles/styles.css
> +  background-color: rgba(130, 179, 211, 0);
Значение четвёртого параметра равное 0 указывает на то, что цвет полностью прозрачный, при этом первые три цифры значения не имеют. Для прозрачного цвета есть ключевое слово `transparent`.

2024-06-19 13:20 UTC, Artem-Sobolev91 commented on styles/styles.css
> +.social-item a :focus {
поставил специально зеленый цвет на состояние , не отображает. Пробел убрал не заработало.

2024-06-24 07:29 UTC, andreysgra requested changes

2024-06-24 07:29 UTC, andreysgra commented on styles/styles.css
>  }
Поскольку вы используете `currentColor` в svg изображении, то должны изменять значение свойства `color` у ссылки не только для `hover`, `active` и `focus`, но и в состоянии покоя (указал это в следующем комментарии).

2024-06-24 07:29 UTC, andreysgra commented on styles/styles.css
>  .social-item a {
Для ссылки нужно добавить `color: #68a2ca;`.

2024-06-24 07:29 UTC, andreysgra commented on styles/styles.css
> +}
А вот здесь `color: #83b3d3;` нужно убрать совсем.

2024-06-24 07:29 UTC, andreysgra commented on styles/styles.css
> +    url(../images/index-background.jpg);
Нужны двойные кавычки.

2024-06-24 07:29 UTC, andreysgra commented on styles/styles.css
> +  font-family: PT Sans;
Должно быть указано типовое семейство для шрифта. Также `PT Sans` нужно заключить в двойные кавычки.

2024-06-25 17:02 UTC, merged